version: '3'
services:
  app:
    container_name: api
    build: .
    ports: 
      - 9009:9009 
    volumes: 
      # - /assets:/var/www/html/files
      - /var/www/html/files:/assets
    restart: on-failure

# volumes: 
#   assets:
#     external: true